# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TFK2nsTYKQS5XbZkrrwMaY9V5q-tJEP0
"""

# importing textblob library
from textblob import TextBlob
t = 1
while t:
    # for incorrect spelling
    a = input("Enter the word to be checked:- ")
    #printing original text
    print("original text: "+str(a))
    b = TextBlob(a)  #correcting the text
    # prints the corrected spelling
    print("corrected text: "+str(b.correct()))
    t = int(input("Try Again? 1 : 0 "))